theme: jekyll-theme-minimal
logo: https://bioboot.github.io/bimm143_W22/assets/img/logo.png
title: Sophia's UCSD Bioinformatics Class Work


# Classwork
-Pertussis [Mini Project](https://github.com/verasophiab/bimm143/blob/main/W10MiniProj/Pertussis_MiniProj_final.pdf)
